/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
<<<<<<< HEAD
=======
    UsePinia: typeof import('./components/usePinia.vue')['default']
>>>>>>> c30492fe47bbc59d71e83e7035278b24ef68ed42
  }
}
